In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler , RobustScaler , MinMaxScaler

In [3]:
df = pd.read_csv('500hits.csv',encoding='latin1')
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [6]:
df.tail()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
460,Jim Wynn,15,1920,6653,1105,1665,285,39,291,964,1224,1427,225,101,0.250,0
461,Jorge Posada,17,1829,6092,900,1664,379,10,275,1065,936,1453,20,21,0.273,0
462,Brady Anderson,15,1834,6499,1062,1661,338,67,210,761,960,1190,315,100,0.256,0
463,Cookie Rojas,16,1822,6309,714,1660,254,25,54,593,396,489,74,68,0.263,0
464,Mickey Rivers,15,1468,5629,785,1660,247,71,61,499,266,471,267,90,0.295,0

In [7]:
df.sample(5)

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
398,Frank Schulte,15,1806,6533,906,1766,288,124,92,0,545,515,233,17,0.270,0
201,Tommy Corcoran,18,2200,8804,1184,2252,289,155,34,0,382,205,387,0,0.256,0
259,Carney Lansford,15,1862,7158,1007,2074,332,40,151,874,553,719,224,104,0.290,0
87,Jim Thome,22,2543,8422,1583,2328,451,26,612,1699,1747,2548,19,20,0.276,1
83,Orlando Cepeda,17,2124,7927,1131,2351,417,27,379,1365,588,1169,142,80,0.297,1

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PLAYER  465 non-null    str
 1   YRS     465 non-null    int64
 2   G       465 non-null    int64
 3   AB      465 non-null    int64
 4   R       465 non-null    int64
 5   H       465 non-null    int64
 6   2B      465 non-null    int64
 7   3B      465 non-null    int64
 8   HR      465 non-null    int64
 9   RBI     465 non-null    int64
 10  BB      465 non-null    int64
 11  SO      465 non-null    int64
 12  SB      465 non-null    int64
 13  CS      465 non-null    int64
 14  BA      465 non-null    float64
 15  HOF     465 non-null    int64
dtypes: float64(1), int64(14), str(1)
memory usage: 58.3 KB

In [5]:
df.describe().round(2)
#df.describe(include=object)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,17.05,2048.70,7511.46,1150.31,2170.25,380.95,78.55,201.05,894.26,783.56,847.47,195.91,58.08,0.29,0.33
std,2.77,354.39,1294.07,289.64,424.19,96.48,49.36,143.62,486.19,327.43,489.22,181.85,48.03,0.02,0.47
min,11.00,1331.00,4981.00,601.00,1660.00,177.00,3.00,9.00,0.00,239.00,0.00,7.00,0.00,0.25,0.00
25%,15.00,1802.00,6523.00,936.00,1838.00,312.00,41.00,79.00,640.00,535.00,436.00,63.00,22.00,0.27,0.00
50%,17.00,1993.00,7241.00,1104.00,2076.00,366.00,67.00,178.00,968.00,736.00,825.00,137.00,52.00,0.29,0.00
75%,19.00,2247.00,8180.00,1296.00,2375.00,436.00,107.00,292.00,1206.00,955.00,1226.00,285.00,84.00,0.30,1.00
max,26.00,3308.00,12364.00,2295.00,4189.00,792.00,309.00,755.00,2297.00,2190.00,2597.00,1406.00,335.00,0.37,2.00

In [6]:
df_new = df.drop(['PLAYER'],axis=1)

df_new.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [8]:
x1 = df_new.iloc[:,:13]
x2 = df_new.iloc[:,:13]

# [row][col]

# [row , col] 

# [: , :]

In [9]:
scaler_standard = StandardScaler() # mean = 0 , std = 1

x1_scaled = scaler_standard.fit_transform(x1)

In [14]:
type(x1)

pandas.DataFrame

In [13]:
type(x1_scaled)

numpy.ndarray

In [8]:
df_new.columns

Index(['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'CS', 'BA', 'HOF'],
      dtype='object')

In [10]:
DF_scaled_standard = pd.DataFrame(x1_scaled , columns = ['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'CS'])

DF_scaled_standard.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,2.499511
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,-0.564531
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,1.478163
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,0.811161
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,-0.898033

In [11]:
df_new.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [12]:
DF_scaled_standard.describe().round(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,-0.00,0.00,0.00,0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.19,-2.03,-1.96,-1.90,-1.20,-2.12,-1.53,-1.34,-1.84,-1.66,-1.73,-1.04,-1.21
25%,-0.74,-0.70,-0.76,-0.74,-0.78,-0.72,-0.76,-0.85,-0.52,-0.76,-0.84,-0.73,-0.75
50%,-0.02,-0.16,-0.21,-0.16,-0.22,-0.16,-0.23,-0.16,0.15,-0.15,-0.05,-0.32,-0.13
75%,0.71,0.56,0.52,0.50,0.48,0.57,0.58,0.63,0.64,0.52,0.77,0.49,0.54
max,3.24,3.56,3.75,3.96,4.76,4.26,4.67,3.86,2.89,4.30,3.58,6.66,5.77

In [13]:
scaler_MinMax = MinMaxScaler(feature_range=(0,1))

x2_scaled = scaler_MinMax.fit_transform(x2)

In [14]:
DF_scaled_MinMax  = pd.DataFrame(x2_scaled , columns = ['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'CS'])

DF_scaled_MinMax.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS
0,0.866667,0.861912,0.874035,0.971074,1.000000,0.889431,0.954248,0.144772,0.316064,0.517683,0.137466,0.632595,0.531343
1,0.733333,0.857360,0.811459,0.795750,0.778964,0.891057,0.568627,0.624665,0.849369,0.697078,0.268002,0.050751,0.092537
2,0.733333,0.737481,0.706217,0.756198,0.733096,1.000000,0.715686,0.144772,0.315194,0.585341,0.084713,0.303788,0.385075
3,0.600000,0.716237,0.841663,0.780401,0.713721,0.596748,0.205882,0.336461,0.570744,0.432086,0.708510,0.250893,0.289552
4,0.666667,0.738998,0.738047,0.670012,0.699881,0.752846,0.813725,0.123324,0.000000,0.371092,0.125915,0.511079,0.044776

In [15]:
DF_scaled_MinMax.describe().round(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,0.40,0.36,0.34,0.32,0.20,0.33,0.25,0.26,0.39,0.28,0.33,0.14,0.17
std,0.18,0.18,0.18,0.17,0.17,0.16,0.16,0.19,0.21,0.17,0.19,0.13,0.14
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.27,0.24,0.21,0.20,0.07,0.22,0.12,0.09,0.28,0.15,0.17,0.04,0.07
50%,0.40,0.33,0.31,0.30,0.16,0.31,0.21,0.23,0.42,0.25,0.32,0.09,0.16
75%,0.53,0.46,0.43,0.41,0.28,0.42,0.34,0.38,0.53,0.37,0.47,0.20,0.25
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00