In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder , StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer

In [2]:
df = pd.read_csv('50_Startups.csv')
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [ ]:
df.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [ ]:
df['State'].nunique()

3

In [ ]:
df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

# 1- make column transformer

In [ ]:
ohe = OneHotEncoder(sparse_output=False)

In [ ]:
ode = OrdinalEncoder()

In [ ]:
ct = make_column_transformer(

    (ohe, ['State']),
    (ode, ['State']),
    remainder='passthrough'

    )

ct.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False),
                                 ['State']),
                                ('ordinalencoder', OrdinalEncoder(),
                                 ['State'])])

In [ ]:
df_new = ct.fit_transform(df)
df_new.head()

,onehotencoder__State_California,onehotencoder__State_Florida,onehotencoder__State_New York,ordinalencoder__State,remainder__R&D Spend,remainder__Administration,remainder__Marketing Spend,remainder__Profit
0,0.0,0.0,1.0,2.0,165349.20,136897.80,471784.10,192261.83
1,1.0,0.0,0.0,0.0,162597.70,151377.59,443898.53,191792.06
2,0.0,1.0,0.0,1.0,153441.51,101145.55,407934.54,191050.39
3,0.0,0.0,1.0,2.0,144372.41,118671.85,383199.62,182901.99
4,0.0,1.0,0.0,1.0,142107.34,91391.77,366168.42,166187.94

In [ ]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
ct2 = make_column_transformer(

    (ohe, ['State']),
    (ode, ['State']),
    remainder='drop'

    )

ct2.set_output(transform='pandas')

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False),
                                 ['State']),
                                ('ordinalencoder', OrdinalEncoder(),
                                 ['State'])])

In [ ]:
df_new_2 = ct2.fit_transform(df)
df_new_2.head()

,onehotencoder__State_California,onehotencoder__State_Florida,onehotencoder__State_New York,ordinalencoder__State
0,0.0,0.0,1.0,2.0
1,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,1.0
3,0.0,0.0,1.0,2.0
4,0.0,1.0,0.0,1.0

In [ ]:
ct3 = make_column_transformer(

    (ohe, ['State']),
    (ode, ['State']),
    ('passthrough', [ 'R&D Spend','Administration' ,'Marketing Spend', 'State','Profit']),
    remainder='drop'

    )

ct3.set_output(transform='pandas')

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False),
                                 ['State']),
                                ('ordinalencoder', OrdinalEncoder(), ['State']),
                                ('passthrough', 'passthrough',
                                 ['R&D Spend', 'Administration',
                                  'Marketing Spend', 'State', 'Profit'])])

In [ ]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [ ]:
df_new_3 = ct3.fit_transform(df)
df_new_3.head()

,onehotencoder__State_California,onehotencoder__State_Florida,onehotencoder__State_New York,ordinalencoder__State,passthrough__R&D Spend,passthrough__Administration,passthrough__Marketing Spend,passthrough__State,passthrough__Profit
0,0.0,0.0,1.0,2.0,165349.20,136897.80,471784.10,New York,192261.83
1,1.0,0.0,0.0,0.0,162597.70,151377.59,443898.53,California,191792.06
2,0.0,1.0,0.0,1.0,153441.51,101145.55,407934.54,Florida,191050.39
3,0.0,0.0,1.0,2.0,144372.41,118671.85,383199.62,New York,182901.99
4,0.0,1.0,0.0,1.0,142107.34,91391.77,366168.42,Florida,166187.94

# 2 - ordinal encoder

In [ ]:
states = list(df['State'].unique())
states

['New York', 'California', 'Florida']

In [ ]:
encoder  = OrdinalEncoder(categories = [states])

encoder.fit_transform(df[['State']])

df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
encoder.fit_transform(df[['State']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.]])

In [ ]:
df['Encoded_State'] = encoder.fit_transform(df[['State']])

#df['state'] = encoder.fit_transform(df[['State']])

In [ ]:
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit,Encoded_State
0,165349.20,136897.80,471784.10,New York,192261.83,0.0
1,162597.70,151377.59,443898.53,California,191792.06,1.0
2,153441.51,101145.55,407934.54,Florida,191050.39,2.0
3,144372.41,118671.85,383199.62,New York,182901.99,0.0
4,142107.34,91391.77,366168.42,Florida,166187.94,2.0

In [ ]:
df.sample(10)

,R&D Spend,Administration,Marketing Spend,State,Profit,Encoded_State
6,134615.46,147198.87,127716.82,California,156122.51,1.0
39,38558.51,82982.09,174999.30,California,81005.76,1.0
23,67532.53,105751.03,304768.73,Florida,108733.99,2.0
45,1000.23,124153.04,1903.93,New York,64926.08,0.0
38,20229.59,65947.93,185265.10,New York,81229.06,0.0
7,130298.13,145530.06,323876.68,Florida,155752.60,2.0
30,61994.48,115641.28,91131.24,Florida,99937.59,2.0
48,542.05,51743.15,0.00,New York,35673.41,0.0
4,142107.34,91391.77,366168.42,Florida,166187.94,2.0
41,27892.92,84710.77,164470.71,Florida,77798.83,2.0

# 3- one hot encoding

In [ ]:
df.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [ ]:
df.State.value_counts()

New York      17
California    17
Florida       16
Name: State, dtype: int64

In [ ]:
encoder_hot = OneHotEncoder(handle_unknown= 'ignore',sparse_output= False).set_output(transform='pandas')

state_encoder_hot = encoder_hot.fit_transform(df[['State']])

state_encoder_hot

    State_California  State_Florida  State_New York
0                0.0            0.0             1.0
1                1.0            0.0             0.0
2                0.0            1.0             0.0
3                0.0            0.0             1.0
4                0.0            1.0             0.0
5                0.0            0.0             1.0
6                1.0            0.0             0.0
7                0.0            1.0             0.0
8                0.0            0.0             1.0
9                1.0            0.0             0.0
10               0.0            1.0             0.0
11               1.0            0.0             0.0
12               0.0            1.0             0.0
13               1.0            0.0             0.0
14               0.0            1.0             0.0
15               0.0            0.0             1.0
16               1.0            0.0             0.0
17               0.0            0.0             1.0
18               0.0            1.0             0.0
19               0.0            0.0             1.0
20               1.0            0.0             0.0
21               0.0            0.0             1.0
22               0.0            1.0             0.0
23               0.0            1.0             0.0
24               0.0            0.0             1.0
25               1.0            0.0             0.0
26               0.0            1.0             0.0
27               0.0            0.0             1.0
28               0.0            1.0             0.0
29               0.0            0.0             1.0
30               0.0            1.0             0.0
31               0.0            0.0             1.0
32               1.0            0.0             0.0
33               0.0            1.0             0.0
34               1.0            0.0             0.0
35               0.0            0.0             1.0
36               0.0            1.0             0.0
37               1.0            0.0             0.0
38               0.0            0.0             1.0
39               1.0            0.0             0.0
40               1.0            0.0             0.0
41               0.0            1.0             0.0
42               1.0            0.0             0.0
43               0.0            0.0             1.0
44               1.0            0.0             0.0
45               0.0            0.0             1.0
46               0.0            1.0             0.0
47               1.0            0.0             0.0
48               0.0            0.0             1.0
49               1.0            0.0             0.0

In [ ]:
df = pd.concat([df, state_encoder_hot], axis=1)
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit,Encoded_State,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,New York,192261.83,0.0,0.0,0.0,1.0
1,162597.70,151377.59,443898.53,California,191792.06,1.0,1.0,0.0,0.0
2,153441.51,101145.55,407934.54,Florida,191050.39,2.0,0.0,1.0,0.0
3,144372.41,118671.85,383199.62,New York,182901.99,0.0,0.0,0.0,1.0
4,142107.34,91391.77,366168.42,Florida,166187.94,2.0,0.0,1.0,0.0

In [3]:
# Split features and target
X = df.drop("Profit", axis=1)
y = df["Profit"]

# Define categorical and numerical columns
categorical_cols = X.select_dtypes(include=['object']).columns
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns

C:\Users\Mahmoud\AppData\Local\Temp\ipykernel_20428\599367799.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=['object']).columns

In [5]:
numerical_cols

Index(['R&D Spend', 'Administration', 'Marketing Spend'], dtype='str')

In [4]:
categorical_cols

Index(['State'], dtype='str')

In [6]:
# Define preprocessing
preprocessor = make_column_transformer(
        (StandardScaler(), numerical_cols),
        (OneHotEncoder(drop='first' ,  sparse_output=False), categorical_cols)
    ).set_output(transform='pandas')

In [ ]:
X.shape, y.shape

((50, 4), (50,))

In [7]:
# Apply preprocessing
X_processed = preprocessor.fit_transform(X)

In [8]:
X_processed.head()

,standardscaler__R&D Spend,standardscaler__Administration,standardscaler__Marketing Spend,onehotencoder__State_Florida,onehotencoder__State_New York
0,2.016411,0.560753,2.153943,0.0,1.0
1,1.955860,1.082807,1.923600,0.0,0.0
2,1.754364,-0.728257,1.626528,1.0,0.0
3,1.554784,-0.096365,1.422210,0.0,1.0
4,1.504937,-1.079919,1.281528,1.0,0.0

In [9]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print("Preprocessing complete. Shape of X_train:", X_train.shape)

Preprocessing complete. Shape of X_train: (40, 5)

In [ ]:
X_train.columns

Index(['standardscaler__R&D Spend', 'standardscaler__Administration',
       'standardscaler__Marketing Spend', 'onehotencoder__State_Florida',
       'onehotencoder__State_New York'],
      dtype='object')

In [ ]:
X_train.describe()

,standardscaler__R&D Spend,standardscaler__Administration,standardscaler__Marketing Spend,onehotencoder__State_Florida,onehotencoder__State_New York
count,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.087283,-0.007273,0.204211,0.350000,0.325000
std,1.054061,0.989829,0.948809,0.483046,0.474342
min,-1.622362,-2.525994,-1.743127,0.000000,0.000000
25%,-0.736793,-0.676557,-0.418563,0.000000,0.000000
50%,0.030866,-0.043623,0.320226,0.000000,0.000000
75%,1.020478,0.887022,0.774789,1.000000,1.000000
max,2.016411,2.210141,2.153943,1.000000,1.000000